language: php
php:
  - '7.3'
  - '7.2'
  - '7.1'
  - '7.0'

install:
  - composer install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - .Build/bin/codacycoverage clover .Build/clover.xml
  - ./cc-test-reporter format-coverage -t clover .Build/clover.xml
  - ./cc-test-reporter upload-coverage