name: Build

on:
  push:
    branches: [ main, develop, 'feature/**', '6.0' ]
  pull_request:
    branches: [ main ]

permissions: read-all

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - { php: 7.4 }
          - { php: 8.0 }
          - { php: 8.1 }
          - { php: 8.2 }
          - { php: 8.3 }
          - { php: 8.4 }
          - { php: 8.5 }

    steps:

    - name: Switch PHP Version
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.env.php }}
        coverage: xdebug

    - uses: actions/checkout@v4

    - name: Validate composer.json
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Build without coverage
      run: composer test